### ISSUE TITLE
Сode examples

### ISSUE THREAD

**Issue by LM-SNC** [jesterret/SteamUserAuthToken#3]
Hey! Are there any code examples with this library?

**Comment by jesterret** [comment]
Hi, I can't promise anything right now, but I can try adding some next week-ish.
Basically, add new SteamAppAuth as a handler to SteamKit SteamClient, then after proceeding with login to steam, as per SteamKit, call the function for specific appid/request app ownership token and pass it in.

**Comment by Anonymous-User47** [comment]
> Hi, I can't promise anything right now, but I can try adding some next week-ish. Basically, add new SteamAppAuth as a handler to SteamKit SteamClient, then after proceeding with login to steam, as per SteamKit, call the function for specific appid/request app ownership token and pass it in.

plz add example code
